### PR TITLE
Improvements

### PR DESCRIPTION
**Pull request by rafa-munoz**
This PR brings many improvements:
1. Updates to the last 2.9.0 version
2. Adds tests to check almost everything
3. Gives the possibility to add more settings to the widget
4. Changes slightly the interface

Regarding changing the interface, it's a necessary change in order
to have tests in the application. Anyway it doesn't break compatibility,
it just marks the old method as deprecated in the console.

### CODE REVIEW

**Comment by rafa-munoz** [comment]
@nate-strauser Looking for your comments :)

**Comment by nate-strauser** [comment]
overall i think this looks really good - but i'd like to change the namespace

let's make it be `UploadCarePlus.load()` - that seems better to me than `UCPlus.loadUploadcare()`

thanks!

**Comment by rafa-munoz** [comment]
@nate-strauser I already did the changes. I agree to what you say, it's much better :)

**Comment by nate-strauser** [comment]
package is published - thanks again!

**Pull request merged**
